### ISSUE TITLE
Sam Object conversion issue

### ISSUE THREAD

**Issue by Tuesday-Last** [codefellows/seattle-javascript-401n1#68]
### What is the expected result?
_ex: What are you trying to accomplish?_  
I'm trying to get the broadcast function to work

### What is the actual result? 
_ex: What are you seeing, or what is happening?_  
the server throws an error saying "Object.keys(ClientPool.pool).forEach(function(clientId){
           ^
TypeError: Cannot convert undefined or null to object "

### What steps have you taken to address the problem? 

1. First I went back to the demo in class but my version of it is getting the same problem
1. Then I looked for any naming conflicts and still am drawing a blank

## Please check these boxes _**after**_ clicking "Submit new issue":
- [ x] I have entered my name and the problem as the title of this issue.
- [ x] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [ x] I have not been able to work through the issue after 15 minutes.

**Comment by ricecreamdude** [comment]
Solved!
