### ISSUE TITLE
Cortney - General help with 'broadcast' function testing

### ISSUE THREAD

**Issue by cdl124** [codefellows/seattle-javascript-401n1#69]
### What is the expected result?
_ex: What are you trying to accomplish?_  
Test my broadcast

### What is the actual result? 
_ex: What are you seeing, or what is happening?_  
I don't see anything related to broadcast when I start up telnet.

### If there is an error message, what is the error message?  
_ex: Uncaught Reference Error: $ is not defined._
None

### What steps have you taken to address the problem? 

1. First I... added my broadcast event to my ClientPool constructor and emit the event within socket.on('data'),
1. Then I... ran node and telnet localhost 3000

## Please check these boxes _**after**_ clicking "Submit new issue":
- [x] I have entered my name and the problem as the title of this issue.
- [x] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [x] I have not been able to work through the issue after 15 minutes.

**Comment by sumtype** [comment]
Walked through issue and resolved to find socket events were being defined within a function but the function itself wasn't being called during runtime.
