### ISSUE TITLE
###(res) is not defined - i don't get this error in server.js

### ISSUE THREAD

**Issue by sjb3** [codefellows/seattle-javascript-401n1#72]
### What is the expected result?
_ex: What are you trying to accomplish?_  

### What is the actual result? 
_ex: What are you seeing, or what is happening?_  

### If there is an error message, what is the error message?  
_ex: Uncaught Reference Error: $ is not defined._

### What steps have you taken to address the problem? 

1. First I...
1. Then I...

## Please check these boxes _**after**_ clicking "Submit new issue":
- [ ] I have entered my name and the problem as the title of this issue.
- [ ] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [ ] I have not been able to work through the issue after 15 minutes.

**Comment by fraziermork** [comment]
fix an undefined variable error.
