### ISSUE TITLE
David Fazio having issues running nodemon

### ISSUE THREAD

**Issue by FazioD** [codefellows/seattle-javascript-401n1#78]
### What is the expected result?
success

_ex: What are you trying to accomplish?_  

automate starting my server using nodemon

### What is the actual result? 
_ex: What are you seeing, or what is happening?_  

cannot run gulp nodemon

### If there is an error message, what is the error message?  
_ex: Uncaught Reference Error: $ is not defined._

Yes. I'm receiving an error that says "cannot find module gulp-nodemon"

### What steps have you taken to address the problem? 

1. First I... have installed the module using npm and saved the dependencies.
1. Then I... checked my gulpfile and ensured that I formatted the task correctly.

## Please check these boxes _**after**_ clicking "Submit new issue":
- [x] I have entered my name and the problem as the title of this issue.
- [x] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [x] I have not been able to work through the issue after 15 minutes.

**Comment by fraziermork** [comment]
Figured it out
